name: Upload Models to S3

on:
  push:
    branches:
      - main  
    paths:
      - "models/**" 

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   

      - name: Upload models folder to S3
        run: |
          aws s3 cp models s3://noideabro/models --recursive
